2019-09-30 12:49:35,278 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-09-30 21:17:09,020 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-09-30 21:17:40,202 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-09-30 21:18:07,730 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-09-30 23:14:27,173 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-09-30 23:48:32,288 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-09-30 23:49:17,683 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-09-30 23:49:37,735 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-10-01 00:41:16,977 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-10-01 00:44:05,690 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-10-01 00:52:45,167 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-10-01 00:56:05,503 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-10-01 00:56:45,882 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-10-01 00:56:51,924 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-10-01 00:58:25,130 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-10-01 00:59:13,005 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-10-01 01:08:29,923 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-10-01 01:26:37,220 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-10-01 01:26:48,270 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-10-01 01:27:12,785 ERROR: Exception on /user/test [GET] [in /home/permi/.local/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/home/permi/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/home/permi/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such column: followers.followed_id

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/permi/.local/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/permi/.local/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/permi/.local/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/permi/.local/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/permi/.local/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/permi/.local/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/permi/.local/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/permi/source/repos/MyMicroblog_flask/src/routes.py", line 74, in user
    return render_template('user.html', user=user, posts=posts)
  File "/home/permi/.local/lib/python3.6/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/permi/.local/lib/python3.6/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/permi/.local/lib/python3.6/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/permi/.local/lib/python3.6/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/permi/.local/lib/python3.6/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/permi/.local/lib/python3.6/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/permi/source/repos/MyMicroblog_flask/src/templates/user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "/home/permi/source/repos/MyMicroblog_flask/src/templates/base.html", line 30, in top-level template code
    {% block content %}{% endblock %}
  File "/home/permi/source/repos/MyMicroblog_flask/src/templates/user.html", line 11, in block "content"
    <p>{{ user.followers.count() }} followers, {{ user.followed.count() }} following.</p>
  File "/home/permi/.local/lib/python3.6/site-packages/sqlalchemy/orm/dynamic.py", line 335, in count
    return self._clone(sess).count()
  File "/home/permi/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3578, in count
    return self.from_self(col).scalar()
  File "/home/permi/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3322, in scalar
    ret = self.one()
  File "/home/permi/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3292, in one
    ret = self.one_or_none()
  File "/home/permi/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3261, in one_or_none
    ret = list(self)
  File "/home/permi/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3334, in __iter__
    return self._execute_and_instances(context)
  File "/home/permi/.local/lib/python3.6/site-packages/sqlalchemy/orm/query.py", line 3359, in _execute_and_instances
    result = conn.execute(querycontext.statement, self._params)
  File "/home/permi/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/home/permi/.local/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/home/permi/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/home/permi/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/home/permi/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/home/permi/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/home/permi/.local/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/home/permi/.local/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/home/permi/.local/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) no such column: followers.followed_id
[SQL: SELECT count(*) AS count_1 
FROM (SELECT user.id AS user_id, user.username AS user_username, user.email AS user_email, user.password_hash AS user_password_hash, user.about_me AS user_about_me, user.last_seen AS user_last_seen 
FROM user, followers 
WHERE followers.followed_id = ? AND followers.follower_id = user.id) AS anon_1]
[parameters: (2,)]
(Background on this error at: http://sqlalche.me/e/e3q8)
2019-10-01 01:27:39,532 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-10-01 01:27:44,725 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-10-01 01:27:52,772 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-10-01 01:29:30,985 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-10-01 01:29:56,079 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
2019-10-01 07:47:28,406 INFO: Microblog startup [in /home/permi/source/repos/MyMicroblog_flask/src/__init__.py:44]
